#!/usr/bin/env python3
import os, sys, git
from pathlib import Path
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('-d', '--dry-run', action='store_true')
args = parser.parse_args()

# ~/.alias_gen
alias_gen_file = Path.home().joinpath(".alias_gen") 

# ~/Documents/
workspace = Path.home().joinpath("Documents/")

if not args.dry_run:
    sys.stdout=open(str(alias_gen_file), "w+")

print("#")
print("# Generated by alia-gen.py")
print("#")

root, folders, files = next(os.walk(workspace))

for folder in sorted(folders):
    try:
        _ = git.Repo(workspace.joinpath(folder)).git_dir # May throw
        alias = ''.join(folder.split()).lower()
        absolute_path=os.path.abspath(os.path.join(root, folder))
        print('alias go2_' + alias + '="cd ' + absolute_path + '"')
    except git.exc.InvalidGitRepositoryError:
        print("# Skipping directory '" + folder + "' because it is not a git repo")
