name: alias_gen
channels:
  - defaults
  - conda-forge
dependencies:
  - sqlite=3.28.0
  - ca-certificates=2019.1.23
  - certifi=2019.3.9
  - gitdb2=2.0.5
  - gitpython=2.1.11
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - ncurses=6.1
  - openssl=1.1.1c
  - pip=18.1
  - python=3.7.3
  - readline=7.0
  - setuptools=40.6.3
  - smmap2=2.0.5
  - tk=8.6.8
  - wheel=0.32.3
  - xz=5.2.4
  - zlib=1.2.11

